name: "Ecr Versioned Push"
description: "Handles pushing a node app to a target repo"
inputs:
    dockerfile-path:
        description: "The path to a specific dockerfile"
        required: true
    repository:
        description: "The repository in AWS"
        required: true
    environment:
        description: "Target environment"
        required: true
    aws-access-key-id:
        description: "AWS access key"
        required: true
    aws-secret-access-key:
        description: "AWS secret access key"
        required: true
    aws-region:
        description: "AWS region"
        required: true
    package-version:
        description: "Package version for tagging"
        required: true
runs:
    using: "composite"
    steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
              aws-access-key-id: ${{ inputs.aws-access-key-id }}
              aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
              REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}
              MAIN_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:v${{ inputs.package-version }}
          run: |
              docker build -t $MAIN_IMAGE -f ${{ inputs.dockerfile-path }} .
              docker tag $MAIN_IMAGE $REPOSITORY:${{ inputs.environment }}
              docker tag $MAIN_IMAGE $REPOSITORY:latest
              docker push --all-tags $REPOSITORY
          shell: bash
